package tb.core;

import java.io.IOException;
import java.util.ArrayList;

import net.minecraftforge.common.MinecraftForge;
import DummyCore.Core.Core;
import tb.api.RevolverUpgrade;
import tb.common.enchantment.EnchantmentHandler;
import tb.common.entity.EntityRevolverBullet;
import tb.common.event.TBEventHandler;
import tb.init.TBBlocks;
import tb.init.TBEnchant;
import tb.init.TBFociUpgrades;
import tb.init.TBItems;
import tb.init.TBRecipes;
import tb.init.TBThaumonomicon;
import tb.init.TBTiles;
import tb.network.proxy.PacketTB;
import tb.network.proxy.TBNetworkManager;
import tb.network.proxy.TBServer;
import tb.utils.TBConfig;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.relauncher.Side;
import static tb.core.TBCore.*;

@Mod(modid = modid, version = version, name = name,dependencies=dependencies)
public class TBCore {

	public static final String modid = "thaumicbases";
	public static final String version = "1.2.1710.3";
	public static final String name = "Thaumic Bases";
	public static final String serverProxy = "tb.network.proxy.TBServer";
	public static final String clientProxy = "tb.network.proxy.TBClient";
	public static final String dependencies = "required-after:Thaumcraft@[4.2.3.5,);required-after:Baubles@[1.0.1.10,);required-after:DummyCore@[1.6,);";
	
	public static final TBConfig cfg = new TBConfig();
	
	@SidedProxy(serverSide = serverProxy,clientSide = clientProxy)
	public static TBServer proxy;
	public static SimpleNetworkWrapper network;
	
	public static TBCore instance;
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		instance = this;
		try
		{
			Core.registerModAbsolute(getClass(), name, event.getModConfigurationDirectory().getAbsolutePath(), cfg);
		}
		catch(IOException ioe)
		{
			FMLCommonHandler.instance().raiseException(ioe, "[ThaumicBases] unable to create cfg file, check your file system!", true);
			return;
		}
		setupModInfo(event.getModMetadata());
		TBBlocks.setup();
		TBItems.setup();
		TBEnchant.setup();
		TBTiles.setup();
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event)
	{
		MinecraftForge.EVENT_BUS.register(new EnchantmentHandler());
		MinecraftForge.EVENT_BUS.register(new TBEventHandler());
		NetworkRegistry.INSTANCE.registerGuiHandler(instance, proxy);
		
		EntityRegistry.registerModEntity(EntityRevolverBullet.class, "revolverBullet", 0, this, 32, 1, true);
		
		TBFociUpgrades.init();
		proxy.registerRenderInformation();
		RevolverUpgrade.initConflictingMappings();
		
		network = NetworkRegistry.INSTANCE.newSimpleChannel("thaumbases");
		network.registerMessage(TBNetworkManager.class, PacketTB.class, 0, Side.SERVER);
		network.registerMessage(TBNetworkManager.class, PacketTB.class, 0, Side.CLIENT);
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event)
	{
		TBRecipes.setup();
		TBThaumonomicon.setup();
	}
	
	public void setupModInfo(ModMetadata meta)
	{
		meta.autogenerated = false;
		meta.modId = modid;
		meta.name = name;
		meta.version = version;
		meta.description = "A Thaumcraft addon, that adds more earlygame and midgame content";
		ArrayList<String> authors = new ArrayList<String>();
		authors.add("Modbder");
		meta.authorList = authors;
	}
}
